version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/decor
    ports:
      - 8000:8000
    environment:
        - DEBUG=1
        - DJANGO_ALLOWED_HOSTS=127.0.0.1 
    image: app:decor
    container_name: decor_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db 
    

  db:
    container_name: postgresql_db
    image: postgres
    # automatically restarts the container - Docker daemon on restart or 
    # the container itself is manually restarted
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always

    volumes:
      - pg_admin:/var/lib/pgadmin

    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
      # PGADMIN_LISTEN_PORT = 80
    ports:
      - "5050:80"



volumes:
  pg_data:
  pg_admin:
